# Version 2.2.0 - 12-27-2017
---

# 6.2.4 Ensure no legacy "+" entries exist in /etc/group

- name: 6.2.4 - Ensure no legacy "+" entries exist in /etc/group
  replace:
    dest: "/etc/group"
    regexp: "^\\+:.*\n"
  tags:
    - level-1
    - section-6
    - "6.2.4"
    - scored
