# Version 2.2.0 - 12-27-2017
---

# 6.2.2 Ensure no legacy "+" entries exist in /etc/passwd

- name: 6.2.2 - Ensure no legacy "+" entries exist in /etc/passwd
  replace:
    dest: "/etc/passwd"
    regexp: "^\\+:.*\n"
  tags:
    - level-1
    - section-6
    - "6.2.2"
    - scored
