# Version 2.2.0 - 12-27-2017
---

# 6.2.3 Ensure no legacy "+" entries exist in /etc/shadow

- name: 6.2.3 - Ensure no legacy "+" entries exist in /etc/shadow
  replace:
    dest: "/etc/shadow"
    regexp: "^\\+:.*\n"
  tags:
    - level-1
    - section-6
    - "6.2.3"
    - scored
