# Version 2.2.0 - 12-27-2017
---

# 2.1.1 Ensure chargen services are not enabled if xinetd is installed

- name: 2.1.1 - Ensure chargen services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: "{{ cis_chargen_state }}"
  with_items:
    - chargen-dgram
    - chargen-stream
  when:  cis_xinetd_state != 'absent'
  tags:
    - level-1
    - section-2
    - "2.1.1"
    - scored
