# Version 2.2.0 - 12-27-2017
---

# 2.3.5 Ensure LDAP client is not installed

- name: 2.3.5 - Ensure LDAP client is not installed
  yum:
    name: "openldap-clients"
    state: absent
  tags:
    - level-1
    - section-2
    - "2.3.5"
    - scored
