# Version 2.2.0 - 12-27-2017
---

- include: preflight.yml
  when: cis_apply_level_1_profile or cis_apply_level_2_profile

- include: "level-1.yml"
  become: yes
  when: cis_apply_level_1_profile

- include: "level-2.yml"
  become: yes
  when: cis_apply_level_2_profile
