# Version 2.2.0 - 12-27-2017
---

# 5.1.3 Ensure permissions on /etc/cron.hourly are configured

- name: 5.1.3 - Ensure permissions on /etc/cron.hourly are configured
  file:
    path: "/etc/cron.hourly"
    owner: root
    group: root
    mode: 0600
  tags:
    - level-1
    - section-5
    - "5.1.3"
    - scored
