# Version 2.2.0 - 12-27-2017
---

# 4.2.2.2 Ensure logging is configured

- name: 4.2.2.2 - Ensure logging is configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-4
    - "4.2.2.2"
    - not-scored
    - todo
